# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

app_statistique_logement:
    path: /statistique/logement
    controller: App\Controller\StatistiqueController::logement
    methods: [GET]

app_statistique_departement:
    path: /statistique/departement
    controller: App\Controller\StatistiqueController::departement
    methods: [GET]

app_statistique_region:
    path: /statistique/region
    controller: App\Controller\StatistiqueController::region
    methods: [GET]
